export class Usergroup {
    GROUP_ID:number;
    SITE_ID:number;
    GROUP_NAME:string;
    GROUP_LEVEL:number;
    PARENT_GROUP:number;
    DESCRIPTION:string;
    FQN_NAME:string;
    CREATED_BY:string;
    WEB:string;
    COUNTRY_ID:string;
    STATE_ID:string;
    CITY_ID:string;
    ADDRESS1:string;
    ADDRESS2:string;
    ZIP:string;
    PHONE:string;
    FAX:string;
    EMAIL:string;
    LANGUAGE_ID:string;
    CURRENCY_ID:string;
    ORGANIZATION_TYPE:string;
    CONTACT_NAME:string;
    CONTACT_PHONE:string;
    CONTACT_EMAIL:string;
    CONTACT_FAX:string;
    CONTACT_MOBILE:string;
    CONTACT_DESIGNATION:string;
}
